# CP7 Step 5 reconstructed targeted threshold-sensitivity analysis.
rm(list=ls())
source(file.path(Sys.getenv("SDY2583_REPO_ROOT",unset="."),"R","shared","reconstructed_panel_framework.R"))
rp_install_and_load(c("dplyr","readr","stringr","tibble","purrr","tidyr"),"flowCore")
source(file.path(sd_repo_root(),"R","panels","CP7","MANIFEST_RECONSTRUCTED.R"))
a<-sd_analysis_dir("CP7"); r<-file.path(a,"11_RData"); out<-file.path(a,"12_threshold_sensitivity"); dir.create(out,recursive=TRUE,showWarnings=FALSE)
load(file.path(r,"SDY2583_CP7_STEP1_fcs_inventory_marker_QC_RECONSTRUCTED.RData")); load(file.path(r,"SDY2583_CP7_STEP3A_metadata_merge_age_QC_RECONSTRUCTED.RData")); metadata_for_merge<-metadata_standardized

extract_cp7<-function(path,thresholds){
 tryCatch({
  obj<-rp_read_transform(path); map<-obj$marker_map; ex<-flowCore::exprs(obj$ff)
  ch<-c(CD3=rp_find_channel(map,c("^CD3$")),CD8=rp_find_channel(map,c("^CD8$")),CD45RA=rp_find_channel(map,c("CD45RA")),CD62L=rp_find_channel(map,c("CD62L")),CD27=rp_find_channel(map,c("^CD27$")),PD1=rp_find_channel(map,c("PD-?1")),TIM3=rp_find_channel(map,c("TIM-?3")),LAG3=rp_find_channel(map,c("LAG-?3")),TIGIT=rp_find_channel(map,c("TIGIT")),ICOS=rp_find_channel(map,c("ICOS")),CD39=rp_find_channel(map,c("CD39")))
  if(any(is.na(ch)))stop("Missing CP7 marker(s): ",paste(names(ch)[is.na(ch)],collapse=", "))
  v<-lapply(ch,function(x)rp_vec(ex,x)); cd3<-v$CD3>thresholds["CD3"]; cd8<-v$CD8>thresholds["CD8"]; gate<-cd3&cd8; ra<-v$CD45RA>thresholds["CD45RA"]; l62<-v$CD62L>thresholds["CD62L"]; cd27<-v$CD27>thresholds["CD27"]; pd1<-v$PD1>thresholds["PD1"]; pd1h<-v$PD1>thresholds["PD1_HIGH"]; tim3<-v$TIM3>thresholds["TIM3"]; lag3<-v$LAG3>thresholds["LAG3"]; tigit<-v$TIGIT>thresholds["TIGIT"]; icos<-v$ICOS>thresholds["ICOS"]; cd39<-v$CD39>thresholds["CD39"]
  naive<-ra&l62; tcm<-!ra&l62; tem<-!ra&!l62; temra<-ra&!l62; temra_neg<-temra&!cd27; temra_pos<-temra&cd27
  tibble::tibble(subject_id=rp_extract_subject_id(path),result_file_name=basename(path),feature_ok=TRUE,error_message=NA_character_,total_events=nrow(ex),n_cd3_pos=rp_n(cd3),n_cd8_pos=rp_n(cd8),n_cd3_cd8_pos=rp_n(gate),pct_cd3_pos_total=rp_pct(cd3),pct_cd8_pos_total=rp_pct(cd8),pct_cd3_cd8_pos_total=rp_pct(gate),pct_cd8_within_cd3=rp_pct(cd8,cd3),median_CD62L_in_CD3CD8=rp_median(v$CD62L[gate]),median_CD27_in_CD3CD8=rp_median(v$CD27[gate]),median_PD1_in_CD3CD8=rp_median(v$PD1[gate]),median_TIM3_in_CD3CD8=rp_median(v$TIM3[gate]),median_LAG3_in_CD3CD8=rp_median(v$LAG3[gate]),median_TIGIT_in_CD3CD8=rp_median(v$TIGIT[gate]),median_ICOS_in_CD3CD8=rp_median(v$ICOS[gate]),median_CD39_in_CD3CD8=rp_median(v$CD39[gate]),median_CD45RA_in_CD3CD8=rp_median(v$CD45RA[gate]),pct_naive_like=rp_pct(naive,gate),pct_tcm_like=rp_pct(tcm,gate),pct_tem_like=rp_pct(tem,gate),pct_temra_like=rp_pct(temra,gate),pct_cd62l_pos_within_cd3cd8=rp_pct(l62,gate),pct_cd62l_neg_within_cd3cd8=rp_pct(!l62,gate),pct_cd45ra_pos_within_cd3cd8=rp_pct(ra,gate),pct_cd45ra_neg_within_cd3cd8=rp_pct(!ra,gate),pct_cd27_pos_within_cd3cd8=rp_pct(cd27,gate),pct_cd27_neg_within_cd3cd8=rp_pct(!cd27,gate),pct_temra_cd27neg=rp_pct(temra_neg,gate),pct_temra_cd27pos=rp_pct(temra_pos,gate),pct_cd62lneg_cd27neg=rp_pct(!l62&!cd27,gate),pct_cd45ra_pos_cd62lneg_cd27neg=rp_pct(ra&!l62&!cd27,gate),pct_naive_cd27pos=rp_pct(naive&cd27,gate),pct_naive_cd27neg=rp_pct(naive&!cd27,gate),pct_pd1_pos=rp_pct(pd1,gate),pct_pd1_high=rp_pct(pd1h,gate),pct_tim3_pos=rp_pct(tim3,gate),pct_lag3_pos=rp_pct(lag3,gate),pct_tigit_pos=rp_pct(tigit,gate),pct_icos_pos=rp_pct(icos,gate),pct_cd39_pos=rp_pct(cd39,gate),pct_pd1_tim3_pos=rp_pct(pd1&tim3,gate),pct_pd1_lag3_pos=rp_pct(pd1&lag3,gate),pct_pd1_tigit_pos=rp_pct(pd1&tigit,gate),pct_pd1_cd39_pos=rp_pct(pd1&cd39,gate),pct_tim3_lag3_pos=rp_pct(tim3&lag3,gate),pct_tigit_cd39_pos=rp_pct(tigit&cd39,gate),pct_icos_cd39_pos=rp_pct(icos&cd39,gate),pct_pd1_tigit_cd39_pos=rp_pct(pd1&tigit&cd39,gate),pct_pd1_tim3_lag3_pos=rp_pct(pd1&tim3&lag3,gate),pct_pd1_tigit_icos_cd39_pos=rp_pct(pd1&tigit&icos&cd39,gate),pct_pd1_pos_within_temra_like=rp_pct(pd1,gate&temra),pct_tim3_pos_within_temra_like=rp_pct(tim3,gate&temra),pct_lag3_pos_within_temra_like=rp_pct(lag3,gate&temra),pct_tigit_pos_within_temra_like=rp_pct(tigit,gate&temra),pct_cd39_pos_within_temra_like=rp_pct(cd39,gate&temra),pct_pd1_pos_within_temra_cd27neg=rp_pct(pd1,gate&temra_neg),pct_tigit_pos_within_temra_cd27neg=rp_pct(tigit,gate&temra_neg),pct_cd39_pos_within_temra_cd27neg=rp_pct(cd39,gate&temra_neg),pct_pd1_temra=rp_pct(pd1&temra,gate),pct_tigit_temra=rp_pct(tigit&temra,gate),pct_cd39_temra=rp_pct(cd39&temra,gate),pct_pd1_temra_cd27neg=rp_pct(pd1&temra_neg,gate),pct_tigit_temra_cd27neg=rp_pct(tigit&temra_neg,gate),pct_cd39_temra_cd27neg=rp_pct(cd39&temra_neg,gate),pct_pd1_tigit_cd39_temra_cd27neg=rp_pct(pd1&tigit&cd39&temra_neg,gate))
 },error=function(e)tibble::tibble(subject_id=rp_extract_subject_id(path),result_file_name=basename(path),feature_ok=FALSE,error_message=conditionMessage(e),total_events=NA_integer_,n_cd3_pos=NA_integer_,n_cd8_pos=NA_integer_,n_cd3_cd8_pos=NA_integer_))
}
main<-CP7_MANIFEST$thresholds; permissive<-main-0.2; stringent<-main+0.2; sets<-list(permissive=permissive,main=main,stringent=stringent); targets<-unique(c(CP7_MANIFEST$targeted_outcomes,CP7_MANIFEST$integrated_score,names(CP7_MANIFEST$score_definitions)))
one_set<-function(label,thresholds){ft<-purrr::map_dfr(fcs_files,~extract_cp7(.x,thresholds)); dat<-ft |> dplyr::left_join(metadata_for_merge,by="subject_id"); scored<-rp_build_scores(dat,CP7_MANIFEST$score_definitions,CP7_MANIFEST$integrated_score); stats<-purrr::map_dfr(targets,~rp_fit_one(scored,.x,label,FALSE,CP7_MANIFEST$primary_event_col,0)) |> dplyr::mutate(targeted_fdr=p.adjust(p_value,"BH"),threshold_set=label); list(data=scored,statistics=stats)}
results<-purrr::imap(sets,one_set); statistics_long<-dplyr::bind_rows(lapply(results,`[[`,"statistics")); summary_wide<-statistics_long |> dplyr::select(threshold_set,feature,beta_cancer_vs_healthy,p_value,targeted_fdr,direction) |> tidyr::pivot_wider(names_from=threshold_set,values_from=c(beta_cancer_vs_healthy,p_value,targeted_fdr,direction)) |> dplyr::mutate(direction_preserved=direction_main==direction_permissive & direction_main==direction_stringent,fdr_preserved=targeted_fdr_main<.05 & targeted_fdr_permissive<.05 & targeted_fdr_stringent<.05,robust_class=dplyr::case_when(direction_preserved&fdr_preserved~"direction_and_FDR_preserved",direction_preserved~"direction_preserved_FDR_not_preserved",TRUE~"direction_not_preserved")); threshold_sets<-purrr::imap_dfr(sets,~tibble::tibble(threshold_set=.y,marker=names(.x),threshold=as.numeric(.x)))
readr::write_csv(threshold_sets,file.path(out,"SDY2583_CP7_threshold_sensitivity_threshold_sets_RECONSTRUCTED.csv")); readr::write_csv(statistics_long,file.path(out,"SDY2583_CP7_threshold_sensitivity_statistics_LONG_RECONSTRUCTED.csv")); readr::write_csv(summary_wide,file.path(out,"SDY2583_CP7_threshold_sensitivity_summary_WIDE_RECONSTRUCTED.csv")); save(results,statistics_long,summary_wide,targets,file=file.path(r,"SDY2583_CP7_STEP5_threshold_sensitivity_RECONSTRUCTED.RData")); print(table(summary_wide$robust_class))
