# CP25 Step 2 reconstructed CD4 regulatory-checkpoint feature extraction.
rm(list=ls())
source(file.path(Sys.getenv("SDY2583_REPO_ROOT",unset="."),"R","shared","reconstructed_panel_framework.R"))
rp_install_and_load(c("dplyr","readr","stringr","tibble","purrr"),"flowCore")
source(file.path(sd_repo_root(),"R","panels","CP25","MANIFEST_RECONSTRUCTED.R"))
panel<-"CP25"; a<-sd_analysis_dir(panel); rdir<-file.path(a,"11_RData"); out<-file.path(a,"02_feature_extraction"); tdir<-file.path(a,"03_thresholds"); dir.create(out,recursive=TRUE,showWarnings=FALSE); dir.create(tdir,recursive=TRUE,showWarnings=FALSE)
load(file.path(rdir,"SDY2583_CP25_STEP1_inventory_RECONSTRUCTED.RData")); th<-CP25_MANIFEST$thresholds
readr::write_csv(tibble::tibble(marker=names(th),threshold=as.numeric(th)),file.path(tdir,"SDY2583_CP25_feature_extraction_thresholds_RECONSTRUCTED.csv"))

extract_one<-function(path,thresholds=th){
 tryCatch({
  obj<-rp_read_transform(path); map<-obj$marker_map; ex<-flowCore::exprs(obj$ff)
  ch<-c(CD25=rp_find_channel(map,c("^CD25$"),"BV421-A"),DUMP=rp_find_channel(map,c("Viability.*CD8.*CD13.*CD19.*TCR","dump","viability"),"BV510-A"),CD3=rp_find_channel(map,c("^CD3$"),"BV605-A"),ICOS=rp_find_channel(map,c("ICOS"),"BV650-A"),CD27=rp_find_channel(map,c("^CD27$"),"BV711-A"),LAG3=rp_find_channel(map,c("LAG-?3"),"BV786-A"),CTLA4=rp_find_channel(map,c("CTLA-?4"),"BB515-A"),CD4=rp_find_channel(map,c("^CD4$"),"PerCP-Cy5-5-A"),IL7RA=rp_find_channel(map,c("IL7RA","CD127"),"PE-A"),PD1=rp_find_channel(map,c("PD-?1"),"PE-CF594-A"),CD45RA=rp_find_channel(map,c("CD45RA"),"PE-Cy5-A"),CD39=rp_find_channel(map,c("CD39"),"PE-Cy7-A"))
  if(any(is.na(ch))) stop("Missing markers: ",paste(names(ch)[is.na(ch)],collapse=", "))
  v<-lapply(ch,function(x) rp_vec(ex,x)); cd3<-v$CD3>thresholds["CD3"]; cd4<-v$CD4>thresholds["CD4"]; dump_low<-v$DUMP<=thresholds["DUMP_LOW"]; raw<-cd3&cd4; primary<-raw&dump_low
  ra<-v$CD45RA>thresholds["CD45RA"]; cd27<-v$CD27>thresholds["CD27"]; cd25<-v$CD25>thresholds["CD25"]; cd25h<-v$CD25>thresholds["CD25_HIGH"]; il7<-v$IL7RA>thresholds["IL7RA"]; il7low<-v$IL7RA<=thresholds["IL7RA"]
  ctla4<-v$CTLA4>thresholds["CTLA4"]; icos<-v$ICOS>thresholds["ICOS"]; cd39<-v$CD39>thresholds["CD39"]; pd1<-v$PD1>thresholds["PD1"]; pd1h<-v$PD1>thresholds["PD1_HIGH"]; lag3<-v$LAG3>thresholds["LAG3"]
  naive<-ra&cd27; memory<-!ra; treg<-cd25&il7low; treg_enriched<-cd25h&il7low; any_reg<-ctla4|icos|cd39|pd1|lag3; any_inhibitory<-ctla4|pd1|lag3
  tibble::tibble(
   total_events=nrow(ex),n_cd3_pos=rp_n(cd3),n_cd4_pos=rp_n(cd4),n_dump_low_total=rp_n(dump_low),n_cd3_cd4_raw=rp_n(raw),n_cd3_cd4_primary=rp_n(primary),
   pct_cd3_pos_total=rp_pct(cd3),pct_cd4_pos_total=rp_pct(cd4),pct_dump_low_total=rp_pct(dump_low),pct_cd3_cd4_raw_total=rp_pct(raw),pct_cd3_cd4_primary_total=rp_pct(primary),pct_cd4_within_cd3_raw=rp_pct(cd4,cd3),pct_cd4_within_cd3_primary=rp_pct(primary,cd3),pct_dump_low_within_cd3_cd4_raw=rp_pct(dump_low,raw),primary_gate="CD3+CD4+dump-low",
   median_CD45RA_in_CD3CD4=rp_median(v$CD45RA[primary]),median_CD27_in_CD3CD4=rp_median(v$CD27[primary]),median_CD25_in_CD3CD4=rp_median(v$CD25[primary]),median_IL7RA_in_CD3CD4=rp_median(v$IL7RA[primary]),median_CTLA4_in_CD3CD4=rp_median(v$CTLA4[primary]),median_ICOS_in_CD3CD4=rp_median(v$ICOS[primary]),median_CD39_in_CD3CD4=rp_median(v$CD39[primary]),median_PD1_in_CD3CD4=rp_median(v$PD1[primary]),median_LAG3_in_CD3CD4=rp_median(v$LAG3[primary]),
   pct_naive_like=rp_pct(naive,primary),pct_memory_like=rp_pct(memory,primary),pct_memory_cd27pos=rp_pct(memory&cd27,primary),pct_memory_cd27neg=rp_pct(memory&!cd27,primary),pct_cd45ra_cd27neg=rp_pct(ra&!cd27,primary),pct_cd27_pos=rp_pct(cd27,primary),pct_cd27_neg=rp_pct(!cd27,primary),
   pct_cd25_pos=rp_pct(cd25,primary),pct_cd25_high=rp_pct(cd25h,primary),pct_il7ra_pos=rp_pct(il7,primary),pct_il7ra_low=rp_pct(il7low,primary),pct_cd25pos_il7ralow_treg_like=rp_pct(treg,primary),pct_cd25high_il7ralow_treg_enriched=rp_pct(treg_enriched,primary),pct_cd25pos_il7ralow_within_memory=rp_pct(treg,primary&memory),
   pct_ctla4_pos=rp_pct(ctla4,primary),pct_icos_pos=rp_pct(icos,primary),pct_cd39_pos=rp_pct(cd39,primary),pct_pd1_pos=rp_pct(pd1,primary),pct_pd1_high=rp_pct(pd1h,primary),pct_lag3_pos=rp_pct(lag3,primary),pct_any_checkpoint_reg_marker=rp_pct(any_reg,primary),pct_any_inhibitory_checkpoint=rp_pct(any_inhibitory,primary),
   pct_pd1_lag3_pos=rp_pct(pd1&lag3,primary),pct_pd1_cd39_pos=rp_pct(pd1&cd39,primary),pct_lag3_cd39_pos=rp_pct(lag3&cd39,primary),pct_ctla4_cd39_pos=rp_pct(ctla4&cd39,primary),pct_icos_cd39_pos=rp_pct(icos&cd39,primary),pct_ctla4_icos_pos=rp_pct(ctla4&icos,primary),pct_pd1_icos_pos=rp_pct(pd1&icos,primary),
   pct_ctla4_treg_like=rp_pct(ctla4&treg,primary),pct_cd39_treg_like=rp_pct(cd39&treg,primary),pct_icos_treg_like=rp_pct(icos&treg,primary),pct_pd1_treg_like=rp_pct(pd1&treg,primary),pct_lag3_treg_like=rp_pct(lag3&treg,primary),pct_ctla4_cd39_treg_like=rp_pct(ctla4&cd39&treg,primary),pct_icos_cd39_treg_like=rp_pct(icos&cd39&treg,primary),pct_pd1_lag3_treg_like=rp_pct(pd1&lag3&treg,primary),
   pct_ctla4pos_within_treg_like=rp_pct(ctla4,primary&treg),pct_cd39pos_within_treg_like=rp_pct(cd39,primary&treg),pct_icospos_within_treg_like=rp_pct(icos,primary&treg),pct_pd1pos_within_treg_like=rp_pct(pd1,primary&treg),pct_lag3pos_within_treg_like=rp_pct(lag3,primary&treg),pct_ctla4_cd39pos_within_treg_like=rp_pct(ctla4&cd39,primary&treg),pct_icos_cd39pos_within_treg_like=rp_pct(icos&cd39,primary&treg),pct_pd1_lag3pos_within_treg_like=rp_pct(pd1&lag3,primary&treg),
   pct_ctla4pos_within_treg_enriched=rp_pct(ctla4,primary&treg_enriched),pct_cd39pos_within_treg_enriched=rp_pct(cd39,primary&treg_enriched),pct_icospos_within_treg_enriched=rp_pct(icos,primary&treg_enriched),pct_pd1pos_within_treg_enriched=rp_pct(pd1,primary&treg_enriched),pct_lag3pos_within_treg_enriched=rp_pct(lag3,primary&treg_enriched),
   pct_ctla4pos_within_memory=rp_pct(ctla4,primary&memory),pct_cd39pos_within_memory=rp_pct(cd39,primary&memory),pct_icospos_within_memory=rp_pct(icos,primary&memory),pct_pd1pos_within_memory=rp_pct(pd1,primary&memory),pct_lag3pos_within_memory=rp_pct(lag3,primary&memory),
   pct_ctla4pos_within_cd39pos=rp_pct(ctla4,primary&cd39),pct_icospos_within_cd39pos=rp_pct(icos,primary&cd39),pct_pd1pos_within_cd39pos=rp_pct(pd1,primary&cd39),pct_lag3pos_within_cd39pos=rp_pct(lag3,primary&cd39),pct_lag3pos_within_pd1pos=rp_pct(lag3,primary&pd1),pct_cd39pos_within_icospos=rp_pct(cd39,primary&icos),
   subject_id=rp_extract_subject_id(path),result_file_name=basename(path),feature_ok=TRUE,error_message=NA_character_)
 },error=function(e) tibble::tibble(total_events=NA_integer_,n_cd3_pos=NA_integer_,n_cd4_pos=NA_integer_,n_dump_low_total=NA_integer_,n_cd3_cd4_raw=NA_integer_,n_cd3_cd4_primary=NA_integer_,subject_id=rp_extract_subject_id(path),result_file_name=basename(path),feature_ok=FALSE,error_message=conditionMessage(e)))
}
feature_table<-purrr::map_dfr(fcs_files,extract_one)
summary<-tibble::tibble(n_files=nrow(feature_table),n_subjects=dplyr::n_distinct(feature_table$subject_id),n_success=sum(feature_table$feature_ok),n_failed=sum(!feature_table$feature_ok),median_total_events=median(feature_table$total_events,na.rm=TRUE),median_raw_cd3cd4_events=median(feature_table$n_cd3_cd4_raw,na.rm=TRUE),median_primary_events=median(feature_table$n_cd3_cd4_primary,na.rm=TRUE),median_dump_low_fraction_within_raw=median(feature_table$pct_dump_low_within_cd3_cd4_raw,na.rm=TRUE))
readr::write_csv(feature_table,file.path(out,"SDY2583_CP25_FULL_850_feature_table_STEP2_RECONSTRUCTED.csv")); readr::write_csv(summary,file.path(out,"SDY2583_CP25_feature_extraction_summary_STEP2_RECONSTRUCTED.csv")); save(feature_table,summary,th,extract_one,file=file.path(rdir,"SDY2583_CP25_STEP2_feature_extraction_RECONSTRUCTED.RData")); print(summary)
