# Build a cross-panel subject-level score matrix from locally generated panel
# outputs. Participant-level integrated data remain excluded from Git.
rm(list=ls());source(file.path(Sys.getenv("SDY2583_REPO_ROOT",unset="."),"R","shared","bootstrap.R"));for(p in c("dplyr","readr","stringr","tibble","purrr","tidyr"))if(!requireNamespace(p,quietly=TRUE))install.packages(p);suppressPackageStartupMessages({library(dplyr);library(readr);library(stringr);library(tibble);library(purrr);library(tidyr)})
panels<-c("CP7","CP8","CP10","CP16","CP22","CP23","CP24","CP25","CP26","CP28");score_pattern<-"^CP[0-9]+_.*_score$|^CP[0-9]+_integrated_"
find_score_file<-function(panel){files<-list.files(sd_analysis_dir(panel),"\\.csv$",full.names=TRUE,recursive=TRUE,ignore.case=TRUE);if(!length(files))return(NA_character_);rank<-1000*grepl("analysis_data_with_composite|score_dataset|with_composite_scores",basename(files),ignore.case=TRUE)-500*grepl("statistics|result|summary|feature_set|map",basename(files),ignore.case=TRUE);files[order(rank,decreasing=TRUE)][1]}
read_scores<-function(panel){path<-find_score_file(panel);if(is.na(path)||!file.exists(path))return(NULL);x<-tryCatch(readr::read_csv(path,show_col_types=FALSE,progress=FALSE),error=function(e)NULL);if(is.null(x))return(NULL);subject_col<-c("subject_id","subject_accession")[c("subject_id","subject_accession")%in%names(x)][1];if(is.na(subject_col))return(NULL);score_cols<-grep(score_pattern,names(x),value=TRUE);if(!length(score_cols))return(NULL);x |> transmute(subject_id=as.character(.data[[subject_col]]),across(all_of(score_cols),as.numeric)) |> group_by(subject_id) |> summarise(across(everything(),~first(na.omit(.x),default=NA_real_)),.groups="drop")}
score_tables<-setNames(lapply(panels,read_scores),panels);available<-names(score_tables)[!vapply(score_tables,is.null,logical(1))];if(!length(available))stop("No panel composite-score datasets were found under outputs/.")
wide<-Reduce(function(x,y)full_join(x,y,by="subject_id"),score_tables[available]);metadata_file<-path.expand(Sys.getenv("SDY2583_METADATA_MATRIX_FILE",unset=file.path(sd_metadata_dir(),"SDY2583_subject_FCS_metadata_matrix_RECONSTRUCTED.csv")));if(file.exists(metadata_file)){metadata<-readr::read_csv(metadata_file,show_col_types=FALSE);metadata<-metadata |> group_by(subject_id) |> summarise(across(everything(),~first(na.omit(.x),default=NA)),.groups="drop");wide<-metadata |> right_join(wide,by="subject_id")}
out_dir<-sd_integrated_dir();dir.create(out_dir,recursive=TRUE,showWarnings=FALSE);manifest<-tibble(panel=panels,score_file=vapply(panels,find_score_file,character(1)),included=panels%in%available,n_score_columns=vapply(score_tables,function(x)if(is.null(x))0L else ncol(x)-1L,integer(1)));readr::write_csv(wide,file.path(out_dir,"SDY2583_integrated_clinical_immune_score_matrix_ALL_PANELS_RECONSTRUCTED.csv"));readr::write_csv(manifest,file.path(out_dir,"SDY2583_cross_panel_score_integration_manifest_RECONSTRUCTED.csv"));cat("Integrated",length(available),"panels and",nrow(wide),"subjects.\n")
