# CP26 Step 5 reconstructed targeted threshold sensitivity (20 outcomes).
rm(list=ls()); source(file.path(Sys.getenv("SDY2583_REPO_ROOT",unset="."),"R","shared","reconstructed_panel_framework.R")); rp_install_and_load(c("dplyr","readr","tibble","purrr","tidyr"),"flowCore"); source(file.path(sd_repo_root(),"R","panels","CP26","MANIFEST_RECONSTRUCTED.R"))
a<-sd_analysis_dir("CP26"); r<-file.path(a,"11_RData"); out<-file.path(a,"12_threshold_sensitivity"); dir.create(out,recursive=TRUE,showWarnings=FALSE)
load(file.path(r,"SDY2583_CP26_STEP2_feature_extraction_RECONSTRUCTED.RData")); load(file.path(r,"SDY2583_CP26_STEP3A_metadata_merge_age_QC_RECONSTRUCTED.RData")); metadata_for_merge<-metadata
main<-CP26_MANIFEST$thresholds; permissive<-main-0.2; stringent<-main+0.2; permissive["DUMP_LOW"]<-main["DUMP_LOW"]+0.2; stringent["DUMP_LOW"]<-main["DUMP_LOW"]-0.2; sets<-list(permissive=permissive,main=main,stringent=stringent)
targets<-c(CP26_MANIFEST$targeted_outcomes,CP26_MANIFEST$integrated_score,names(CP26_MANIFEST$score_definitions)); stopifnot(length(targets)==20)
one_set<-function(label,thresholds){ft<-purrr::map_dfr(fcs_files,~extract_one(.x,thresholds)); dat<-ft |> dplyr::left_join(metadata_for_merge,by="subject_id"); scored<-rp_build_scores(dat,CP26_MANIFEST$score_definitions,CP26_MANIFEST$integrated_score); stats<-purrr::map_dfr(targets,~rp_fit_one(scored,.x,label,FALSE,CP26_MANIFEST$primary_event_col,0)) |> dplyr::mutate(targeted_fdr=p.adjust(p_value,"BH"),threshold_set=label); list(data=scored,statistics=stats)}
results<-purrr::imap(sets,one_set); statistics_long<-dplyr::bind_rows(lapply(results,`[[`,"statistics")); robustness<-statistics_long |> dplyr::select(threshold_set,feature,beta_cancer_vs_healthy,p_value,targeted_fdr,direction) |> tidyr::pivot_wider(names_from=threshold_set,values_from=c(beta_cancer_vs_healthy,p_value,targeted_fdr,direction)) |> dplyr::mutate(direction_preserved=direction_main==direction_permissive & direction_main==direction_stringent,fdr_preserved=targeted_fdr_main<.05 & targeted_fdr_permissive<.05 & targeted_fdr_stringent<.05,robust_class=dplyr::case_when(direction_preserved&fdr_preserved~"direction_and_FDR_preserved_all_sets",direction_preserved~"direction_preserved_FDR_not_all_sets",TRUE~"direction_not_preserved"))
threshold_sets<-purrr::imap_dfr(sets,~tibble::tibble(threshold_set=.y,marker=names(.x),threshold=as.numeric(.x))); counts<-robustness |> dplyr::count(robust_class,name="n_variables")
readr::write_csv(threshold_sets,file.path(out,"SDY2583_CP26_threshold_sets_STEP5_RECONSTRUCTED.csv")); readr::write_csv(statistics_long,file.path(out,"SDY2583_CP26_threshold_sensitivity_statistics_STEP5_RECONSTRUCTED.csv")); readr::write_csv(robustness,file.path(out,"SDY2583_CP26_threshold_sensitivity_robustness_STEP5_RECONSTRUCTED.csv")); readr::write_csv(counts,file.path(out,"SDY2583_CP26_threshold_sensitivity_robustness_counts_STEP5_RECONSTRUCTED.csv")); save(results,statistics_long,robustness,counts,targets,file=file.path(r,"SDY2583_CP26_STEP5_threshold_sensitivity_RECONSTRUCTED.RData")); print(counts)
