# CP28 Step 2 reconstructed T/NK-interface feature extraction.
rm(list=ls())
source(file.path(Sys.getenv("SDY2583_REPO_ROOT",unset="."),"R","shared","reconstructed_panel_framework.R"))
rp_install_and_load(c("dplyr","readr","stringr","tibble","purrr"),"flowCore")
source(file.path(sd_repo_root(),"R","panels","CP28","MANIFEST_RECONSTRUCTED.R"))
panel<-"CP28"; a<-sd_analysis_dir(panel); r<-file.path(a,"11_RData"); out<-file.path(a,"02_feature_extraction"); td<-file.path(a,"03_thresholds"); dir.create(out,recursive=TRUE,showWarnings=FALSE); dir.create(td,recursive=TRUE,showWarnings=FALSE)
load(file.path(r,"SDY2583_CP28_STEP1_inventory_RECONSTRUCTED.RData")); th<-CP28_MANIFEST$thresholds; readr::write_csv(tibble::tibble(marker=names(th),threshold=as.numeric(th)),file.path(td,"SDY2583_CP28_feature_extraction_thresholds_TNK_interface_RECONSTRUCTED.csv"))

extract_one<-function(path,thresholds=th){
 tryCatch({
  obj<-rp_read_transform(path); map<-obj$marker_map; ex<-flowCore::exprs(obj$ff)
  ch<-c(DUMP=rp_find_channel(map,c("dump","viability"),"BV510-A"),CD3=rp_find_channel(map,c("^CD3$"),"BV605-A"),VA24=rp_find_channel(map,c("Va24","V.?24.*J.?11"),"BV650-A"),VDELTA2=rp_find_channel(map,c("Vdelta2","V.?delta.?2"),"BV711-A"),CD57=rp_find_channel(map,c("^CD57$"),"BV786-A"),CD27=rp_find_channel(map,c("^CD27$"),"BB515-A"),CD8=rp_find_channel(map,c("^CD8$"),"PerCP-Cy5-5-A"),CD161=rp_find_channel(map,c("CD161"),"PE-A"),CD56=rp_find_channel(map,c("^CD56$"),"PE-CF594-A"),CD45RA=rp_find_channel(map,c("CD45RA"),"PE-Cy5-A"),VALPHA7=rp_find_channel(map,c("Valpha7","V.?alpha.?7"),"PE-Cy7-A"))
  if(any(is.na(ch))) stop("Missing CP28 markers: ",paste(names(ch)[is.na(ch)],collapse=", "))
  v<-lapply(ch,function(x)rp_vec(ex,x)); dump<-v$DUMP<=thresholds["DUMP_LOW"]; cd3<-v$CD3>thresholds["CD3"]; cd8<-v$CD8>thresholds["CD8"]; ra<-v$CD45RA>thresholds["CD45RA"]; cd27<-v$CD27>thresholds["CD27"]; cd57<-v$CD57>thresholds["CD57"]; cd56<-v$CD56>thresholds["CD56"]; cd161<-v$CD161>thresholds["CD161"]; vd2<-v$VDELTA2>thresholds["VDELTA2"]; va24<-v$VA24>thresholds["VA24_JA11_TCR"]; va7<-v$VALPHA7>thresholds["VALPHA7"]
  cd3d<-dump&cd3; cd3neg<-dump&!cd3; cd8d<-dump&cd8; cd3cd8<-dump&cd3&cd8; nk<-dump&!cd3&cd56; naive<-ra&cd27; memory<-!ra; temra<-ra&!cd27
  tibble::tibble(
   total_events=nrow(ex),n_dump_low=rp_n(dump),n_cd3_pos_dump_low=rp_n(cd3d),n_cd3_neg_dump_low=rp_n(cd3neg),n_cd8_pos_dump_low=rp_n(cd8d),n_cd3_cd8_pos=rp_n(cd3cd8),n_cd3neg_cd56pos_nk_like=rp_n(nk),
   pct_dump_low_total=rp_pct(dump),pct_cd3_pos_total=rp_pct(cd3d),pct_cd3_pos_within_dump_low=rp_pct(cd3,dump),pct_cd3_neg_within_dump_low=rp_pct(!cd3,dump),pct_cd8_pos_total=rp_pct(cd8d),pct_cd8_pos_within_dump_low=rp_pct(cd8,dump),pct_cd3_cd8_pos_total=rp_pct(cd3cd8),pct_cd3_cd8_pos_within_dump_low=rp_pct(cd3&cd8,dump),pct_cd8_within_cd3=rp_pct(cd8,cd3d),pct_cd3_within_cd8=rp_pct(cd3,cd8d),
   pct_cd3neg_cd56pos_nk_like_total=rp_pct(nk),pct_cd3neg_cd56pos_nk_like_within_dump_low=rp_pct(!cd3&cd56,dump),pct_cd3neg_cd56pos_nk_like_within_cd3neg=rp_pct(cd56,cd3neg),pct_cd57pos_within_cd3neg_cd56pos_nk_like=rp_pct(cd57,nk),pct_cd8pos_within_cd3neg_cd56pos_nk_like=rp_pct(cd8,nk),pct_cd57_cd8_pos_within_cd3neg_cd56pos_nk_like=rp_pct(cd57&cd8,nk),
   median_CD8_in_CD3=rp_median(v$CD8[cd3d]),median_CD56_in_CD3=rp_median(v$CD56[cd3d]),median_CD57_in_CD3=rp_median(v$CD57[cd3d]),median_CD161_in_CD3=rp_median(v$CD161[cd3d]),median_Vdelta2_in_CD3=rp_median(v$VDELTA2[cd3d]),median_Va24Ja11_in_CD3=rp_median(v$VA24[cd3d]),median_Valpha7_in_CD3=rp_median(v$VALPHA7[cd3d]),
   pct_cd8_pos_within_cd3=rp_pct(cd8,cd3d),pct_cd56_pos_within_cd3=rp_pct(cd56,cd3d),pct_cd57_pos_within_cd3=rp_pct(cd57,cd3d),pct_cd161_pos_within_cd3=rp_pct(cd161,cd3d),pct_vdelta2_pos_within_cd3=rp_pct(vd2,cd3d),pct_va24ja11_pos_within_cd3=rp_pct(va24,cd3d),pct_valpha7_pos_within_cd3=rp_pct(va7,cd3d),pct_valpha7_cd161_pos_within_cd3=rp_pct(va7&cd161,cd3d),pct_cd56_cd57_pos_within_cd3=rp_pct(cd56&cd57,cd3d),pct_cd8_cd57_pos_within_cd3=rp_pct(cd8&cd57,cd3d),pct_cd8_cd56_pos_within_cd3=rp_pct(cd8&cd56,cd3d),pct_cd8_cd161_pos_within_cd3=rp_pct(cd8&cd161,cd3d),pct_vdelta2_cd8_pos_within_cd3=rp_pct(vd2&cd8,cd3d),pct_va24ja11_cd8_pos_within_cd3=rp_pct(va24&cd8,cd3d),pct_valpha7_cd161_cd8_pos_within_cd3=rp_pct(va7&cd161&cd8,cd3d),pct_cd8pos_within_vdelta2_cd3=rp_pct(cd8,cd3d&vd2),pct_cd8pos_within_va24ja11_cd3=rp_pct(cd8,cd3d&va24),pct_cd161pos_within_valpha7_cd3=rp_pct(cd161,cd3d&va7),pct_valpha7pos_within_cd161_cd3=rp_pct(va7,cd3d&cd161),
   median_CD45RA_in_CD3CD8=rp_median(v$CD45RA[cd3cd8]),median_CD27_in_CD3CD8=rp_median(v$CD27[cd3cd8]),median_CD57_in_CD3CD8=rp_median(v$CD57[cd3cd8]),median_CD56_in_CD3CD8=rp_median(v$CD56[cd3cd8]),median_CD161_in_CD3CD8=rp_median(v$CD161[cd3cd8]),median_Vdelta2_in_CD3CD8=rp_median(v$VDELTA2[cd3cd8]),median_Va24Ja11_in_CD3CD8=rp_median(v$VA24[cd3cd8]),median_Valpha7_in_CD3CD8=rp_median(v$VALPHA7[cd3cd8]),
   pct_cd8_naive_like=rp_pct(naive,cd3cd8),pct_cd8_memory_like=rp_pct(memory,cd3cd8),pct_cd8_temra_like=rp_pct(temra,cd3cd8),pct_cd8_cd45ra_pos=rp_pct(ra,cd3cd8),pct_cd8_cd27_pos=rp_pct(cd27,cd3cd8),pct_cd8_cd27_neg=rp_pct(!cd27,cd3cd8),pct_cd57_pos_within_cd8=rp_pct(cd57,cd3cd8),pct_cd56_pos_within_cd8=rp_pct(cd56,cd3cd8),pct_cd161_pos_within_cd8=rp_pct(cd161,cd3cd8),pct_vdelta2_pos_within_cd8=rp_pct(vd2,cd3cd8),pct_va24ja11_pos_within_cd8=rp_pct(va24,cd3cd8),pct_valpha7_pos_within_cd8=rp_pct(va7,cd3cd8),pct_valpha7_cd161_pos_within_cd8=rp_pct(va7&cd161,cd3cd8),pct_cd57_cd27neg_within_cd8=rp_pct(cd57&!cd27,cd3cd8),pct_cd57_temra_within_cd8=rp_pct(cd57&temra,cd3cd8),pct_cd56_cd57_within_cd8=rp_pct(cd56&cd57,cd3cd8),pct_cd56_temra_within_cd8=rp_pct(cd56&temra,cd3cd8),pct_cd57pos_within_cd8_temra=rp_pct(cd57,cd3cd8&temra),pct_cd56pos_within_cd8_temra=rp_pct(cd56,cd3cd8&temra),pct_cd161pos_within_valpha7_cd8=rp_pct(cd161,cd3cd8&va7),pct_valpha7pos_within_cd161_cd8=rp_pct(va7,cd3cd8&cd161),
   result_file_name=basename(path),fcs_path=normalizePath(path,mustWork=FALSE),subject_id=rp_extract_subject_id(path),feature_ok=TRUE,error_message=NA_character_)
 },error=function(e)tibble::tibble(total_events=NA_integer_,n_dump_low=NA_integer_,n_cd3_pos_dump_low=NA_integer_,n_cd3_neg_dump_low=NA_integer_,n_cd8_pos_dump_low=NA_integer_,n_cd3_cd8_pos=NA_integer_,n_cd3neg_cd56pos_nk_like=NA_integer_,result_file_name=basename(path),fcs_path=normalizePath(path,mustWork=FALSE),subject_id=rp_extract_subject_id(path),feature_ok=FALSE,error_message=conditionMessage(e)))
}
feature_table<-purrr::map_dfr(fcs_files,extract_one); summary<-tibble::tibble(n_files=nrow(feature_table),n_subjects=dplyr::n_distinct(feature_table$subject_id),n_success=sum(feature_table$feature_ok),n_failed=sum(!feature_table$feature_ok),median_total_events=median(feature_table$total_events,na.rm=TRUE),min_total_events=min(feature_table$total_events,na.rm=TRUE),max_total_events=max(feature_table$total_events,na.rm=TRUE),median_dump_low_events=median(feature_table$n_dump_low,na.rm=TRUE),median_cd3_dump_low_events=median(feature_table$n_cd3_pos_dump_low,na.rm=TRUE),median_cd3_cd8_events=median(feature_table$n_cd3_cd8_pos,na.rm=TRUE),median_cd3neg_cd56pos_events=median(feature_table$n_cd3neg_cd56pos_nk_like,na.rm=TRUE))
readr::write_csv(feature_table,file.path(out,"SDY2583_CP28_FULL_850_feature_table_STEP2_TNK_interface_RECONSTRUCTED.csv")); readr::write_csv(summary,file.path(out,"SDY2583_CP28_feature_extraction_summary_STEP2_TNK_interface_RECONSTRUCTED.csv")); save(feature_table,summary,th,extract_one,file=file.path(r,"SDY2583_CP28_STEP2_feature_extraction_RECONSTRUCTED.RData")); print(summary)
