# Structural and optional archive validation for recovered/SAFE panel pipelines.
source(file.path(Sys.getenv("SDY2583_REPO_ROOT",unset="."),"R","shared","reconstructed_panel_framework.R")); rp_install_and_load(c("dplyr","readr","tibble"))
panel<-toupper(Sys.getenv("SDY2583_CURRENT_PANEL",unset="")); if(!panel %in% c("CP10","CP16","CP22","CP23"))stop("Set SDY2583_CURRENT_PANEL to CP10, CP16, CP22, or CP23.")
a<-sd_analysis_dir(panel); out<-file.path(a,"validation"); dir.create(out,recursive=TRUE,showWarnings=FALSE); status_file<-file.path(out,paste0("SDY2583_",panel,"_pipeline_execution_status.csv")); status<-if(file.exists(status_file))readr::read_csv(status_file,show_col_types=FALSE)else tibble::tibble(status="missing")
all_files<-list.files(a,full.names=TRUE,recursive=TRUE); rdata_files<-all_files[grepl("\\.(RData|rds)$",all_files,ignore.case=TRUE)]; csv_files<-all_files[grepl("\\.csv$",all_files,ignore.case=TRUE)]; figure_files<-all_files[grepl("\\.(pdf|png|tiff?)$",all_files,ignore.case=TRUE)]
expected_steps<-switch(panel,CP10=c("STEP1","STEP1B","STEP2","STEP3A","STEP3B","STEP4","STEP4B","STEP5","STEP6","STEP7A","STEP7B","STEP8"),CP16=c("STEP1","STEP1B","STEP2","STEP3A","STEP3B","STEP4","STEP4B","STEP5","STEP6","STEP7A","STEP7B"),CP22=c("STEP1","STEP1B","STEP2","STEP3A","STEP3B","STEP4","STEP4B","STEP5","STEP6","STEP7A","STEP7B"),CP23=c("STEP1","STEP1B","STEP2","STEP3A","STEP3B","STEP4","STEP4B","STEP5","STEP6","STEP6B","STEP7A","STEP7B"))
step_presence<-vapply(expected_steps,function(s)any(grepl(s,basename(rdata_files),ignore.case=TRUE)|grepl(s,basename(csv_files),ignore.case=TRUE)),logical(1))
checks<-tibble::tibble(check=c("all scripts completed","RData outputs present","CSV outputs present","figure outputs present",paste0("output evidence for ",expected_steps)),observed=c(if(nrow(status))paste(unique(status$status),collapse=";")else"missing",length(rdata_files),length(csv_files),length(figure_files),as.character(step_presence)),expected=c("completed",">= 1",">= 1",">= 1",rep("TRUE",length(expected_steps))),pass=c(nrow(status)>0&&all(status$status=="completed"),length(rdata_files)>=1,length(csv_files)>=1,length(figure_files)>=1,step_presence))
# Optional reference inventory comparison: compare relative CSV names rather than participant data.
ref<-path.expand(Sys.getenv(paste0("SDY2583_",panel,"_REFERENCE_DIR"),unset="")); if(nzchar(ref)&&dir.exists(ref)){generated_names<-sort(unique(basename(csv_files)));reference_names<-sort(unique(basename(list.files(ref,"\\.csv$",full.names=TRUE,recursive=TRUE,ignore.case=TRUE))));missing_reference_names<-setdiff(reference_names,generated_names);checks<-dplyr::bind_rows(checks,tibble::tibble(check="archived CSV basenames reproduced",observed=length(missing_reference_names),expected=0,pass=length(missing_reference_names)==0))}
readr::write_csv(checks,file.path(out,paste0("SDY2583_",panel,"_recovered_pipeline_validation_report.csv")));print(checks,n=nrow(checks));if(any(!checks$pass))stop(panel," recovered pipeline validation failed.")
