# CP8 Step 4B reconstructed age strata, matching, and interaction analyses.
rm(list=ls())
source(file.path(Sys.getenv("SDY2583_REPO_ROOT", unset="."),"R","shared","reconstructed_panel_framework.R"))
rp_install_and_load(c("dplyr","readr","tibble","purrr"))
source(file.path(sd_repo_root(),"R","panels","CP8","MANIFEST_RECONSTRUCTED.R"))
analysis_dir<-sd_analysis_dir("CP8"); rdata_dir<-file.path(analysis_dir,"11_RData"); out_dir<-file.path(analysis_dir,"10_age_sensitivity"); dir.create(out_dir,recursive=TRUE,showWarnings=FALSE)
load(file.path(rdata_dir,"SDY2583_CP8_STEP4_composite_scores_RECONSTRUCTED.RData"))
outcomes<-unique(c(CP8_MANIFEST$targeted_outcomes,CP8_MANIFEST$integrated_score,names(CP8_MANIFEST$score_definitions)))
result<-rp_age_sensitivity(scored_data,outcomes,event_col=CP8_MANIFEST$primary_event_col,min_events=0,calipers=c(5,10))
readr::write_csv(result$stratified,file.path(out_dir,"SDY2583_CP8_age_stratified_statistics_RECONSTRUCTED.csv")); readr::write_csv(result$matched,file.path(out_dir,"SDY2583_CP8_age_matched_sensitivity_statistics_RECONSTRUCTED.csv")); readr::write_csv(result$match_summary,file.path(out_dir,"SDY2583_CP8_age_matched_sensitivity_summary_RECONSTRUCTED.csv")); readr::write_csv(result$interactions,file.path(out_dir,"SDY2583_CP8_disease_by_age_interaction_statistics_RECONSTRUCTED.csv"))
for(n in names(result$matched_data)) readr::write_csv(result$matched_data[[n]],file.path(out_dir,paste0("SDY2583_CP8_age_matched_dataset_caliper_",n,"y_RECONSTRUCTED.csv")))
save(result,outcomes,file=file.path(rdata_dir,"SDY2583_CP8_STEP4B_age_sensitivity_RECONSTRUCTED.RData")); print(result$match_summary)
