# CP8 Step 4 reconstructed composite scores.
rm(list=ls())
source(file.path(Sys.getenv("SDY2583_REPO_ROOT", unset="."),"R","shared","reconstructed_panel_framework.R"))
rp_install_and_load(c("dplyr","readr","tibble","purrr"))
source(file.path(sd_repo_root(),"R","panels","CP8","MANIFEST_RECONSTRUCTED.R"))
analysis_dir<-sd_analysis_dir("CP8"); rdata_dir<-file.path(analysis_dir,"11_RData"); out_dir<-file.path(analysis_dir,"08_composite_scores"); dir.create(out_dir,recursive=TRUE,showWarnings=FALSE)
load(file.path(rdata_dir,"SDY2583_CP8_STEP3A_metadata_merge_age_QC_RECONSTRUCTED.RData"))
scored_data<-rp_build_scores(analysis_data,CP8_MANIFEST$score_definitions,CP8_MANIFEST$integrated_score)
score_names<-c(CP8_MANIFEST$integrated_score,names(CP8_MANIFEST$score_definitions))
score_statistics<-rp_fit_scores(scored_data,score_names)
binary_score_statistics<-rp_fit_scores(scored_data,score_names,binary_sex=TRUE)
feature_sets<-purrr::imap_dfr(CP8_MANIFEST$score_definitions,~tibble::tibble(score_name=.y,positive_features=paste(.x$positive,collapse="; "),negative_features=paste(.x$negative,collapse="; "))) |> dplyr::bind_rows(tibble::tibble(score_name=CP8_MANIFEST$integrated_score,positive_features=paste(names(CP8_MANIFEST$score_definitions),collapse="; "),negative_features=""))
readr::write_csv(feature_sets,file.path(out_dir,"SDY2583_CP8_composite_score_feature_sets_RECONSTRUCTED.csv")); readr::write_csv(scored_data,file.path(out_dir,"SDY2583_CP8_analysis_data_with_composite_scores_RECONSTRUCTED.csv")); readr::write_csv(score_statistics,file.path(out_dir,"SDY2583_CP8_composite_score_statistics_RECONSTRUCTED.csv")); readr::write_csv(binary_score_statistics,file.path(out_dir,"SDY2583_CP8_composite_score_binary_sex_sensitivity_statistics_RECONSTRUCTED.csv"))
save(scored_data,score_statistics,binary_score_statistics,feature_sets,file=file.path(rdata_dir,"SDY2583_CP8_STEP4_composite_scores_RECONSTRUCTED.RData")); print(score_statistics)
